# Settings
DEBUG = True

# Board
BOARD_ROWS            = 25
BOARD_COLUMNS         = 25
BOARD_BOMB_PERCENTAGE = 0.2

# Size of cells
CELL_SIZE = 25
CELL_BORDER = 2

# Colors
BACKGROUND_COLOR   = (26, 26, 26)
BORDER_COLOR       = (100, 100, 100)
TEXT_COLOR         = (255, 255, 255)
UNDISCOVERED_COLOR = (160, 160, 160)

# Cells
BOMB         = -2
UNDISCOVERED = -1
EMPTY        =  0
ONE_BOMB     =  1
TWO_BOMBS    =  2
THREE_BOMBS  =  3
FOUR_BOMBS   =  4
FIVE_BOMBS   =  5
SIX_BOMBS    =  6
SEVEN_BOMBS  =  7
EIGHT_BOMBS  =  8

# Window
PADDING       = 20
SCREEN_WIDTH  = (2 * PADDING + CELL_BORDER + BOARD_COLUMNS * (CELL_SIZE + CELL_BORDER))
SCREEN_HEIGHT = (2 * PADDING + CELL_BORDER + BOARD_ROWS * (CELL_SIZE + CELL_BORDER))
